server:
  port: 8080
mongo:
  uri: "mongodb://devflow:devflow@192.168.1.2:32282/devflow?authSource=devflow"
  db: "devflow"
log:
  level: "info"
  format: "json"   # json | console
otel:
  endpoint: "127.0.0.1:4317"
  service_name: "devflow"
repo:
  address: "https://github.com/bsonger/manifests.git"
  path: "manifests"